# Generated by Django 5.1.4 on 2026-09-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanimport',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanimport',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='scan_imports', to='core.host'),
        ),
        migrations.AddField(
            model_name='scanimport',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scanimport',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanimport',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vulnerabilityfinding',
            name='detection_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vulnerabilityfinding',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='host',
            name='qualys_host_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
