# Generated by Django 5.1.4 on 2026-09-23 15:13

from django.db import migrations, models


def backfill_qualys_severity(apps, schema_editor):
    # Definitions imported before the Qualys level was stored: recover it
    # where the mapping is one-to-one. "low" was 1 or 2, so it stays empty
    # until the next import reports it.
    Definition = apps.get_model("core", "VulnerabilityDefinition")
    for severity, level in {"critical": 5, "high": 4, "medium": 3}.items():
        Definition.objects.filter(severity=severity, qualys_severity__isnull=True).update(qualys_severity=level)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perimeters'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='cvss_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='cvss_severity',
            field=models.CharField(blank=True, help_text='NVD rating, e.g. CRITICAL', max_length=16),
        ),
        migrations.AddField(
            model_name='cve',
            name='cvss_source',
            field=models.CharField(blank=True, help_text='Who scored it: NVD or the CNA', max_length=100),
        ),
        migrations.AddField(
            model_name='cve',
            name='cvss_vector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cve',
            name='cvss_version',
            field=models.CharField(blank=True, help_text='e.g. 3.1', max_length=8),
        ),
        migrations.AddField(
            model_name='cve',
            name='nvd_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cve',
            name='nvd_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='nvd_last_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='nvd_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='nvd_status',
            field=models.CharField(choices=[('pending', 'Not fetched yet'), ('ok', 'Fetched'), ('not_found', 'Not in NVD'), ('error', 'Fetch failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='vulnerabilitydefinition',
            name='qualys_severity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, '5 Urgent'), (4, '4 Critical'), (3, '3 Serious'), (2, '2 Medium'), (1, '1 Minimal')], null=True),
        ),
        migrations.RunPython(backfill_qualys_severity, migrations.RunPython.noop),
    ]
