# Generated by Django 5.1.4 on 2026-09-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_qualys_severity_nvd_cvss'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='ubuntu_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cve',
            name='ubuntu_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='ubuntu_packages',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cve',
            name='ubuntu_priority',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='cve',
            name='ubuntu_status',
            field=models.CharField(choices=[('pending', 'Not fetched yet'), ('ok', 'Fetched'), ('not_found', 'Not in NVD'), ('error', 'Fetch failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='distropatchverification',
            name='from_patch_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distropatchverification',
            name='package_versions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='host',
            name='patch_check_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='host',
            name='patch_check_state',
            field=models.CharField(blank=True, help_text='running, done or failed', max_length=16),
        ),
        migrations.AddField(
            model_name='host',
            name='patch_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ubuntu_release',
            field=models.CharField(blank=True, choices=[('resolute', 'Ubuntu 26.04 LTS (resolute)'), ('questing', 'Ubuntu 25.10 (questing)'), ('plucky', 'Ubuntu 25.04 (plucky)'), ('noble', 'Ubuntu 24.04 LTS (noble)'), ('jammy', 'Ubuntu 22.04 LTS (jammy)'), ('focal', 'Ubuntu 20.04 LTS (focal)'), ('bionic', 'Ubuntu 18.04 LTS (bionic)'), ('xenial', 'Ubuntu 16.04 LTS (xenial)'), ('trusty', 'Ubuntu 14.04 LTS (trusty)')], max_length=16),
        ),
        migrations.AddField(
            model_name='installedpackage',
            name='source_package',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='installedpackage',
            name='source_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='installedpackage',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('pasted', 'Pasted list'), ('import', 'Scan import')], default='import', max_length=16),
        ),
        migrations.CreateModel(
            name='PatchCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('fixed', 'Fixed in the installed version'), ('not_affected', 'Not affected'), ('vulnerable_update', 'Vulnerable, update available'), ('vulnerable_pro', 'Vulnerable, fix needs Ubuntu Pro (ESM)'), ('vulnerable_no_fix', 'Vulnerable, no fix yet'), ('unknown', 'Cannot verify')], max_length=32)),
                ('ubuntu_release', models.CharField(max_length=16)),
                ('details', models.JSONField(blank=True, default=list)),
                ('package_versions', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField()),
                ('vulnerability_finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patch_check', to='core.vulnerabilityfinding')),
            ],
        ),
    ]
