# Generated by Django 5.1.4 on 2026-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ubuntu_patch_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('name', models.CharField(default='Load balancer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
        migrations.AddField(
            model_name='host',
            name='private_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
