# Generated by Django 5.1.4 on 2026-09-23 20:33

from django.db import migrations, models


DESCRIPTIONS = {
    "Scanned by the Qualys scanner appliance inside the network": "Scanned by the Qualys Scanner Appliance Inside the Network",
    "Scanned from the internet by Qualys": "Scanned from the Internet by Qualys",
}


def title_case_perimeter_descriptions(apps, schema_editor):
    # Only the default texts: a description an admin changed is left alone.
    Perimeter = apps.get_model("core", "Perimeter")
    for old, new in DESCRIPTIONS.items():
        Perimeter.objects.filter(description=old).update(description=new)


def back(apps, schema_editor):
    Perimeter = apps.get_model("core", "Perimeter")
    for old, new in DESCRIPTIONS.items():
        Perimeter.objects.filter(description=new).update(description=old)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_private_ip_load_balancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cvss_severity',
            field=models.CharField(blank=True, help_text='NVD Rating, e.g. CRITICAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cvss_source',
            field=models.CharField(blank=True, help_text='Who Scored It: NVD or the CNA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cve',
            name='nvd_status',
            field=models.CharField(choices=[('pending', 'Not Fetched Yet'), ('ok', 'Fetched'), ('not_found', 'Not in NVD'), ('error', 'Fetch Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='cve',
            name='ubuntu_status',
            field=models.CharField(choices=[('pending', 'Not Fetched Yet'), ('ok', 'Fetched'), ('not_found', 'Not in NVD'), ('error', 'Fetch Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='distropatchverification',
            name='verdict',
            field=models.CharField(choices=[('likely_false_positive', 'Likely False Positive'), ('confirmed_vulnerable', 'Confirmed Vulnerable'), ('confirmed_fixed', 'Confirmed Fixed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_version',
            field=models.CharField(blank=True, help_text="Distro and Release, e.g. 'Ubuntu 20.04'", max_length=100),
        ),
        migrations.AlterField(
            model_name='installedpackage',
            name='installed_version',
            field=models.CharField(help_text='Full Version String, Including Distro Revision', max_length=255),
        ),
        migrations.AlterField(
            model_name='installedpackage',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('pasted', 'Pasted List'), ('import', 'Scan Import')], default='import', max_length=16),
        ),
        migrations.AlterField(
            model_name='patchcheck',
            name='verdict',
            field=models.CharField(choices=[('fixed', 'Fixed in the Installed Version'), ('not_affected', 'Not Affected'), ('vulnerable_update', 'Vulnerable, Update Available'), ('vulnerable_pro', 'Vulnerable, Fix Needs Ubuntu Pro (ESM)'), ('vulnerable_no_fix', 'Vulnerable, No Fix Yet'), ('unknown', 'Cannot Verify')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scanimport',
            name='raw_file_path',
            field=models.CharField(blank=True, help_text='Where the Original Report Is Archived, for Re-Processing', max_length=500),
        ),
        migrations.AlterField(
            model_name='scanimport',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('api', 'Automatic (API)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='vulnerabilityfinding',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('still_open', 'Still Open'), ('needs_review', 'Needs Review'), ('resolved', 'Resolved')], default='new', max_length=16),
        ),
        migrations.RunPython(title_case_perimeter_descriptions, back),
    ]
