# Generated by Django 5.1.4 on 2026-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_title_case_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanimport',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
