# Generated by Django 5.1.4 on 2026-09-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_import_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KevEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=32, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('short_description', models.TextField(blank=True)),
                ('required_action', models.TextField(blank=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('ransomware', models.BooleanField(default=False, help_text='Known to Be Used in Ransomware Campaigns')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CISA KEV entry',
                'verbose_name_plural': 'CISA KEV entries',
                'ordering': ['-date_added'],
            },
        ),
    ]
