# Generated by Django 5.1.4 on 2026-09-24 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_epss_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='running_kernel',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_host_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_pending_host_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_state',
            field=models.CharField(blank=True, help_text='running, done, failed or host_key', max_length=16),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='installedpackage',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('pasted', 'Pasted List'), ('import', 'Scan Import'), ('ssh', 'Read over SSH')], default='import', max_length=16),
        ),
        migrations.CreateModel(
            name='SshKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(max_length=32)),
                ('public_key', models.TextField()),
                ('fingerprint', models.CharField(max_length=80)),
                ('private_key_encrypted', models.TextField()),
                ('origin', models.CharField(choices=[('generated', 'Generated in Pvm'), ('uploaded', 'Uploaded')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSH key',
            },
        ),
    ]
