# Generated by Django 5.1.4 on 2026-09-24 14:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ssh_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_tag_name_ci')],
            },
        ),
        migrations.AddField(
            model_name='host',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='core.tag'),
        ),
        migrations.AddField(
            model_name='scanimport',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='scan_imports', to='core.tag'),
        ),
    ]
