# Generated by Django 5.1.4 on 2026-09-25 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanimport',
            name='qualys_scan_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='scanimport',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('qualys', 'From Qualys'), ('api', 'Automatic (API)')], max_length=16),
        ),
        migrations.CreateModel(
            name='QualysImportRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_title', models.CharField(max_length=255, unique=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=16)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('at_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('perimeter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualys_rules', to='core.perimeter')),
                ('tags', models.ManyToManyField(blank=True, related_name='qualys_rules', to='core.tag')),
            ],
            options={
                'ordering': ['scan_title'],
            },
        ),
        migrations.AddField(
            model_name='scanimport',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='core.qualysimportrule'),
        ),
        migrations.AddConstraint(
            model_name='scanimport',
            constraint=models.UniqueConstraint(condition=models.Q(('qualys_scan_ref', ''), _negated=True), fields=('qualys_scan_ref',), name='unique_qualys_scan_import'),
        ),
    ]
