# Generated by Django 5.1.4 on 2026-09-25 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_qualys_scans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedpackage',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('pasted', 'Pasted List'), ('import', 'Scan Import'), ('qualys_agent', 'Qualys Cloud Agent'), ('ssh', 'Read over SSH')], default='import', max_length=16),
        ),
        migrations.CreateModel(
            name='CsamSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('running', 'Searching'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assets_seen', models.PositiveIntegerField(default=0)),
                ('hosts_total', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('api_calls', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CsamProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.BigIntegerField()),
                ('qualys_host_id', models.CharField(blank=True, max_length=64)),
                ('asset_name', models.CharField(blank=True, max_length=255)),
                ('matched_by', models.CharField(max_length=32)),
                ('os_full', models.CharField(blank=True, max_length=255)),
                ('ubuntu_release', models.CharField(blank=True, max_length=16)),
                ('inventory_source', models.CharField(blank=True, max_length=32)),
                ('agent_checked_in', models.DateTimeField(blank=True, null=True)),
                ('qualys_tags', models.JSONField(blank=True, default=list)),
                ('criticality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('packages', models.JSONField(blank=True, default=list)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csam_proposals', to='core.host')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.csamsearch')),
            ],
            options={
                'ordering': ['host__hostname'],
            },
        ),
    ]
