# Generated by Django 5.1.4 on 2026-09-25 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_qualys_csam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateIpMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('private_ip', models.GenericIPAddressField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['public_ip', 'hostname'],
                'constraints': [models.UniqueConstraint(fields=('public_ip', 'hostname'), name='unique_private_ip_mapping')],
            },
        ),
    ]
