# Generated by Django 5.1.4 on 2026-09-26 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_private_ip_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. A10, or A10 plus the device's host name", max_length=100, unique=True)),
                ('product', models.CharField(blank=True, help_text='e.g. A10 ACOS 4.1.4-GR1-P9', max_length=100)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BalancerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_name', models.CharField(blank=True, max_length=255)),
                ('vip_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.CharField(blank=True, help_text='e.g. 443/https', max_length=32)),
                ('match', models.CharField(blank=True, choices=[('', 'Any Name'), ('equals', 'Equals'), ('starts-with', 'Starts With'), ('ends-with', 'Ends With'), ('contains', 'Contains'), ('regex-match', 'Regex')], max_length=16)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('service_group', models.CharField(max_length=255)),
                ('backend_ips', models.JSONField(default=list)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.balancerconfig')),
            ],
            options={
                'ordering': ['config', 'vip_ip', 'port', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='HostPrivateIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('position', models.PositiveIntegerField(default=1)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_private_ips', to='core.host')),
            ],
            options={
                'ordering': ['host', 'position'],
                'constraints': [models.UniqueConstraint(fields=('host', 'ip_address'), name='unique_host_private_ip')],
            },
        ),
    ]
