# Generated by Django 5.1.4 on 2026-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_balancer_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='patch_check_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='patch_check_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
