# Generated by Django 5.1.4 on 2026-09-29 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_history_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distropatchverification',
            name='source',
            field=models.CharField(choices=[('ubuntu_tracker', 'Ubuntu Security Tracker'), ('qualys_pm', 'Qualys Patch Management')], default='ubuntu_tracker', max_length=16),
        ),
        migrations.AddField(
            model_name='patchcheck',
            name='source',
            field=models.CharField(choices=[('ubuntu_tracker', 'Ubuntu Security Tracker'), ('qualys_pm', 'Qualys Patch Management')], default='ubuntu_tracker', max_length=16),
        ),
        migrations.AlterField(
            model_name='patchcheck',
            name='ubuntu_release',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='PmSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('running', 'Searching'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('windows_hosts', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('patches_seen', models.PositiveIntegerField(default=0)),
                ('findings_checked', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('fixed_count', models.PositiveIntegerField(default=0)),
                ('unknown_count', models.PositiveIntegerField(default=0)),
                ('api_calls', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
