# Generated by Django 5.1.4 on 2026-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_qualys_patch_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='rocky_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cve',
            name='rocky_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='rocky_packages',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cve',
            name='rocky_priority',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='cve',
            name='rocky_status',
            field=models.CharField(choices=[('pending', 'Not Fetched Yet'), ('ok', 'Fetched'), ('not_found', 'Not in NVD'), ('error', 'Fetch Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='host',
            name='rocky_release',
            field=models.CharField(blank=True, choices=[('10', 'Rocky Linux 10'), ('9', 'Rocky Linux 9'), ('8', 'Rocky Linux 8')], max_length=8),
        ),
        migrations.AlterField(
            model_name='distropatchverification',
            name='source',
            field=models.CharField(choices=[('ubuntu_tracker', 'Ubuntu Security Tracker'), ('qualys_pm', 'Qualys Patch Management'), ('rocky_tracker', 'Rocky Linux Errata')], default='ubuntu_tracker', max_length=16),
        ),
        migrations.AlterField(
            model_name='patchcheck',
            name='source',
            field=models.CharField(choices=[('ubuntu_tracker', 'Ubuntu Security Tracker'), ('qualys_pm', 'Qualys Patch Management'), ('rocky_tracker', 'Rocky Linux Errata')], default='ubuntu_tracker', max_length=16),
        ),
    ]
