# Generated by Django 5.1.4 on 2026-09-23 14:37

import accounts.models
from django.db import migrations, models


def superusers_to_super_admin(apps, schema_editor):
    # Existing superusers were created with the default read-only role.
    apps.get_model("accounts", "User").objects.filter(is_superuser=True).update(role="superadmin")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.PVMUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('analyst', 'Analyst'), ('readonly', 'Read-only')], default='readonly', max_length=16),
        ),
        migrations.RunPython(superusers_to_super_admin, migrations.RunPython.noop),
    ]
