# Generated by Django 5.1.4 on 2026-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_super_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('analyst', 'Analyst'), ('readonly', 'Read-only')], max_length=16),
        ),
    ]
