# Generated by Django 5.1.4 on 2026-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local (TOTP)'), ('sso', 'Single Sign-On')], default='local', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('analyst', 'Analyst'), ('readonly', 'Read-Only')], max_length=16),
        ),
    ]
