from django.urls import path

from . import csam_views, export_views, host_views, import_views, network_views, patch_views, qualys_pm_views, qualys_views, ssh_views, triage_views, views

app_name = "core"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("vulnerabilities/", views.vulnerability_list, name="vulnerability_list"),
    path("vulnerabilities/qid/<str:qid>/", views.vulnerability_detail, name="vulnerability_detail"),
    path("vulnerabilities/triage/", triage_views.triage_findings, name="triage_findings"),
    path("hosts/", views.host_list, name="host_list"),
    path("hosts/export.csv", views.host_export, name="host_export"),
    path("export/", export_views.page, name="export"),
    path("export/preview/", export_views.preview, name="export_preview"),
    path("export/run/", export_views.run, name="export_run"),
    path("vulnerabilities/export.csv", views.vulnerability_export, name="vulnerability_export"),
    path("ssh/", ssh_views.settings_page, name="ssh_access"),
    path("ssh/key/generate/", ssh_views.generate_key, name="ssh_generate_key"),
    path("ssh/key/upload/", ssh_views.upload_key, name="ssh_upload_key"),
    path("ssh/key/delete/", ssh_views.delete_key, name="ssh_delete_key"),
    path("ssh/ask-all/", ssh_views.ask_all, name="ssh_ask_all"),
    path("hosts/<int:pk>/ssh/", ssh_views.host_settings, name="host_ssh_settings"),
    path("hosts/<int:pk>/ssh/trust/", ssh_views.trust_host_key, name="host_ssh_trust"),
    path("hosts/<int:pk>/ssh/forget/", ssh_views.forget_host_key, name="host_ssh_forget"),
    path("hosts/<int:pk>/ssh/ask/", ssh_views.ask, name="host_ask_server"),
    path("hosts/<int:pk>/", views.host_detail, name="host_detail"),
    path("hosts/<int:pk>/network/", host_views.update_network, name="host_update_network"),
    path("hosts/<int:pk>/tags/", host_views.add_tags, name="host_add_tags"),
    path("hosts/<int:pk>/tags/<int:tag_pk>/remove/", host_views.remove_tag, name="host_remove_tag"),
    path("hosts/<int:pk>/release/", patch_views.set_release, name="host_set_release"),
    path("hosts/<int:pk>/packages/paste/", patch_views.paste_inventory, name="host_paste_inventory"),
    path("hosts/<int:pk>/packages/add/", patch_views.add_package, name="host_add_package"),
    path("hosts/<int:pk>/packages/<int:package_pk>/share/", patch_views.share_package, name="host_share_package"),
    path("hosts/<int:pk>/packages/<int:package_pk>/delete/", patch_views.delete_package, name="host_delete_package"),
    path("hosts/<int:pk>/check/", patch_views.run_check, name="host_run_check"),
    path("hosts/<int:pk>/confirm-fixed/", patch_views.confirm_all_fixed, name="host_confirm_all_fixed"),
    path("findings/<int:finding_pk>/confirm-check/", patch_views.confirm_check, name="finding_confirm_check"),
    path("imports/", import_views.import_list, name="import_list"),
    path("imports/new/", import_views.import_upload, name="import_upload"),
    path("imports/backup/", import_views.import_backup, name="import_backup"),
    path("imports/backup/upload/", import_views.import_backup_upload, name="import_backup_upload"),
    path("imports/qualys/", qualys_views.scans, name="qualys_scans"),
    path("imports/csam/", csam_views.page, name="qualys_csam"),
    path("imports/pm/", qualys_pm_views.page, name="qualys_pm"),
    path("imports/pm/search/", qualys_pm_views.start, name="qualys_pm_search"),
    path("imports/mapping/", network_views.page, name="network_mapping"),
    path("imports/mapping/upload/", network_views.upload, name="network_mapping_upload"),
    path("imports/mapping/apply/", network_views.apply, name="network_mapping_apply"),
    path("imports/mapping/clear/", network_views.clear, name="network_mapping_clear"),
    path("imports/mapping/balancers/<int:pk>/delete/", network_views.delete_config, name="balancer_config_delete"),
    path("imports/csam/search/", csam_views.start, name="qualys_csam_search"),
    path("imports/csam/import/", csam_views.import_selected, name="qualys_csam_import"),
    path("imports/qualys/import/", qualys_views.import_scan, name="qualys_import"),
    path("imports/qualys/rules/new/", qualys_views.rule_form, name="qualys_rule_new"),
    path("imports/qualys/rules/<int:pk>/", qualys_views.rule_form, name="qualys_rule_edit"),
    path("imports/qualys/rules/<int:pk>/toggle/", qualys_views.rule_toggle, name="qualys_rule_toggle"),
    path("imports/qualys/rules/<int:pk>/delete/", qualys_views.rule_delete, name="qualys_rule_delete"),
    path("imports/<int:pk>/", import_views.import_detail, name="import_detail"),
    path("imports/<int:pk>/columns/", import_views.import_mapping, name="import_mapping"),
    path("imports/<int:pk>/stop/", import_views.import_stop, name="import_stop"),
    path("imports/<int:pk>/discard/", import_views.import_discard, name="import_discard"),
    path("imports/<int:pk>/rename/", import_views.import_rename, name="import_rename"),
    path("imports/<int:pk>/tags/", import_views.import_add_tags, name="import_add_tags"),
]
