# Generated by Django 5.1.4 on 2026-09-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('pre_import', 'Before import'), ('pre_restore', 'Before restore')], max_length=16)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, help_text='Username, kept as text on purpose', max_length=150)),
                ('scan_import_id', models.PositiveBigIntegerField(blank=True, help_text='For pre-import backups', null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('contents', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restored_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
