# Generated by Django 5.1.4 on 2026-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_pre_reset_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='created_by',
            field=models.CharField(blank=True, help_text='Username, Kept as Text on Purpose', max_length=150),
        ),
        migrations.AlterField(
            model_name='backup',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('pre_import', 'Before Import'), ('pre_restore', 'Before Restore'), ('pre_reset', 'Before Data Reset')], max_length=16),
        ),
        migrations.AlterField(
            model_name='backup',
            name='scan_import_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='For Pre-Import Backups', null=True),
        ),
    ]
