# Generated by Django 5.1.4 on 2026-09-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_title_case_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('pre_import', 'Before Import'), ('pre_restore', 'Before Restore'), ('pre_reset', 'Before Data Reset'), ('pre_mapping', 'Before Mapping')], max_length=16),
        ),
    ]
