# Generated by Django 5.1.4 on 2026-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_pre_mapping_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='full',
            field=models.BooleanField(default=False, help_text='Also includes the raw Qualys report files (scan imports)'),
        ),
    ]
